<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
    <gazebo>
      <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <legacyMode>false</legacyMode>
        <alwaysOn>true</alwaysOn>
        <updateRate>1000.0</updateRate>
        <leftJoint>${left_wheel_joint}</leftJoint>
        <rightJoint>${right_wheel_joint}</rightJoint>
        <wheelSeparation>${wheel_separation}</wheelSeparation>
        <wheelDiameter>${2*wheel_radius}</wheelDiameter>
        <wheelTorque>10</wheelTorque>
        <publishTf>1</publishTf>
        <odometryFrame>map</odometryFrame>
        <commandTopic>mobile_base_controller/cmd_vel</commandTopic>
        <odometryTopic>mobile_base_controller/odom</odometryTopic>
        <robotBaseFrame>base_footprint</robotBaseFrame>
        <wheelAcceleration>2.8</wheelAcceleration>
        <publishWheelJointState>true</publishWheelJointState>
        <publishWheelTF>false</publishWheelTF>
        <odometrySource>world</odometrySource>
        <rosDebugLevel>Debug</rosDebugLevel>
      </plugin>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_wheel_friction" params="link friction">
    <gazebo reference="${link}">
      <mu1 value="${friction}"/>
      <mu2 value="${friction}"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <minDepth>0.01</minDepth>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="set_all_wheel_frictions" params="prefix">
    <xacro:set_wheel_friction link="${prefix}left_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}right_wheel_link" friction="200"/>
    <xacro:set_wheel_friction link="${prefix}fl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}fr_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}bl_caster_wheel_link" friction="1"/>
    <xacro:set_wheel_friction link="${prefix}br_caster_wheel_link" friction="1"/>
  </xacro:macro>

  <xacro:macro name="p3d_base_controller" params="prefix">
    <gazebo>
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>50.0</updateRate>
        <bodyName>${prefix}base_footprint</bodyName>
        <topicName>base_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>0 0 0</xyzOffsets>
        <rpyOffsets>0 0 0</rpyOffsets>
      </plugin>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="camera" params="prefix">

<joint name="camera_sensor_joint" type="fixed">
            <axis xyz="0 1 0" />
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <parent link="${prefix}base_footprint"/>
            <child link="camera_link"/>
        </joint>
        
        <link name="camera_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.08 0.05"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.08 0.05"/>
                </geometry>
                <material name="iRobot/Green"/>
            </visual>
            <inertial>
                <mass value="0.0001" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.0000001" ixy="0" ixz="0" iyy="0.0000001" iyz="0" izz="0.0000001" />
            </inertial>
        </link>
        
        
        
        <gazebo reference="camera_link">
            <sensor type="camera" name="camera">
                <update_rate>30.0</update_rate>
                <camera name="head">
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>800</width>
                        <height>600</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>iRobot/camera</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
    </gazebo>

  </xacro:macro>



</robot>
